### PR TITLE
Ignore non-TPTP output from vampire

### PR DESCRIPTION
**Pull request by MGlauer**
This *should* solve #10. @sfluegel05 can you test?

### CODE REVIEW

**Comment by sfluegel05** [comment]
I still get the same error message as before.

**Comment by MGlauer** [comment]
Oh, there were some bug in the tff grammar, that led to the same bug, but from a different origin.

**Comment by MGlauer** [comment]
@sfluegel05 There were some uncommited changes, that I did not deem relevant. As it turns out, they were. It works with the file that you supplied in #10

**Review by sfluegel05 — APPROVED** [review]
Now everything works fine, thanks for fixing this.

**Pull request merged**
